Move Request types to dependencies
nodevault/node-vault pull request #146
Opened 2020-03-02 17:41 UTC by Kamahl19

@types/request needs to be a dependency instead of devDependency. If we build a library with node-vault as dependency, @types/request are missing

2020-03-02 17:42 UTC, Kamahl19 commented
@kr1sp1n This fixes the issue introduced in https://github.com/kr1sp1n/node-vault/pull/142

2020-03-30 17:36 UTC, Kamahl19 commented
@kr1sp1n Could you please take a look on this one? It fixes 2 bugs with types introduced lately.

2022-11-10 17:32 UTC, aviadhahami commented
@Kamahl19 do you mind removing the `package.json` change?

2022-11-10 17:32 UTC, aviadhahami requested changes

2025-06-07 21:54 UTC, aviadhahami commented
addressed in https://github.com/nodevault/node-vault/pull/257

2025-06-07 21:54 UTC, closed without merging